# Generated by Django 5.2.3 on 2025-07-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cveapp", "0002_track_host_track"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HostCVE",
        ),
    ]
