# Generated by Django 5.2.3 on 2025-07-02 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cveapp", "0003_delete_hostcve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cve",
            name="cve_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cve",
            name="impact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cve",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="host",
            name="os_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="host",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cveapp.track",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
